name: SpigotConsole
version: 1.05
api-version: 1.13
description: Brings the console to you
author: Kyllian
main: me.kyllian.spigotconsole.SpigotConsolePlugin

commands:
  spigotconsole:
    description: Base command of the plugin
    aliases: [sc]
    usage: /<command>